
"""
Collect all constant definitions here
"""
from .__version__ import __version__
from .parameters import STARTDATE_TS, ENDDATE_TS, INTERVAL_TS, COORDINATES_TS, PARAMETERS_TS, MODEL, ENS_SELECT, CLUSTER_SELECT

API_BASE_URL = "https://api.meteomatics.com"

VERSION = f"python_v{__version__}"


NA_VALUES = (-666, -777, -888, -999)

LOGGERNAME="ts-ex" #input("What would you like to name the logger?")

# templates
TIME_SERIES_TEMPLATE = "{API_BASE_URL}/{STARTDATE_TS}--{ENDDATE_TS}:{INTERVAL_TS}/{PARAMETERS_TS}/{COORDINATES_TS}/bin?{urlParams}"
GRID_TEMPLATE = "{API_BASE_URL}/{STARTDATE}/{PARAMETER_GRID}/{LAT_N},{LON_W}_{LAT_S},{LON_E}:{RES_LAT},{RES_LON}/bin?{URL_PARAMS}"
GRID_TIME_SERIES_TEMPLATE = "{API_BASE_URL}/{STARTDATE}--{ENDDATE}:{INTERVAL}/{PARAMETERS}/{LAT_N},{LON_W}_{LAT_S},{LON_E}:{RES_LAT},{RES_LON}/bin?{URL_PARAMS}"
POLYGON_TEMPLATE = "{API_BASE_URL}/{STARTDATE}--{ENDDATE}:{INTERVAL}/{PARAMETERS}/{COORDINATES_AGGREGATION}/csv?{URL_PARAMS}"
GRID_PNG_TEMPLATE = "{API_BASE_URL}/{STARTDATE}/{PARAMETER_GRID}/{LAT_N},{LON_W}_{LAT_S},{LON_E}:{RES_LAT},{RES_LON}/png?{URL_PARAMS}"
LIGHTNING_TEMPLATE = "{API_BASE_URL}/get_lightning_list?time_range={STARTDATE}--{ENDDATE}&bounding_box={LAT_N},{LON_W}_{LAT_S},{LON_E}&source={SOURCE}&format=csv"
NETCDF_TEMPLATE = "{API_BASE_URL}/{STARTDATE}--{ENDDATE}:{INTERVAL}/{PARAMETER_NETCDF}/{LAT_N},{LON_W}_{LAT_S},{LON_E}:{RES_LAT},{RES_LON}/netcdf?{URL_PARAMS}"
STATIONS_LIST_TEMPLATE = "{API_BASE_URL}/find_station?{URL_PARAMS}"
INIT_DATE_TEMPLATE = "{API_BASE_URL}/get_init_date?model={MODEL}&valid_date={INTERVAL_STRING}&parameters={PARAMETER}"
AVAILABLE_TIME_RANGES_TEMPLATE = "{API_BASE_URL}/get_time_range?model={MODEL}&parameters={PARAMETERS}"

logdepth = 0